### ISSUE TITLE
Header: Contact us should be aligned with the social media icon as per design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#49]
![image](https://cloud.githubusercontent.com/assets/12791909/9679692/60b04100-5323-11e5-86f6-280174ba6dd1.png)

**Comment by nakul-titan** [comment]
Currently Contact us menu item is having padding around it. In order to make it align with social media icons, we have to remove that padding which will disturb the look of contact us menu item when mouseover it.

![siteware-direct-bug-screen](https://cloud.githubusercontent.com/assets/13461911/9713154/205b6da4-556d-11e5-81be-a8bc094a658b.jpg)

**Comment by ermatitan** [comment]
This is a valid issue as per the design. If this can't be implemented as for some reason please label it as won't fix. Thanks

**Comment by nakul-titan** [comment]
The designer might not be aware of the fact of the pudding concerns, plus that's a prototype. However while developing we have to look into all the considerations. Removing padding wont solve the purpose. So this shouldn't be an issue.

Kindly If you could discuss with your TL, may be he can conclude.
So this is an invalid issue, so 'won't fix' won't be appropriate label. :-)
